services:
  reverse-proxy:
    image: nginx:1.27-alpine
    container_name: reverse-proxy
    ports:
      - "8443:443"
    volumes:
        - ./reverse-proxy/spa.conf:/etc/nginx/conf.d/spa.conf:ro
        - ./reverse-proxy/certs/localhost.crt:/etc/nginx/certs/dev.crt:ro
        - ./reverse-proxy/certs/localhost.key:/etc/nginx/certs/dev.key:ro
        - ./reverse-proxy/html:/usr/share/nginx/html:ro
    networks:
      - web

networks:
  web:
    driver: bridge

